# Generated by Django 5.2.8 on 2025-12-15 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('office_address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street_number', models.CharField(max_length=6)),
                ('office_phone', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_structured', models.BooleanField(default=False)),
                ('is_long', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_key', models.CharField(max_length=100)),
                ('custom_value', models.CharField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='SoulDiaryConnectApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('fiscal_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='SoulDiaryConnectApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_text', models.TextField()),
                ('support_text', models.TextField(blank=True, null=True)),
                ('clinical_text', models.TextField()),
                ('doctor_note', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='SoulDiaryConnectApp.patient')),
            ],
        ),
    ]
